name: add json

on:
  pull_request:
    types: 
      - closed
    paths:
      - "./data/**.json"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: adding json files
        run: cat ./data/*.json > ./finish/merged.json
