name: add json

on:
  pull_request:
    types: [closed]
    paths:
      - "**.json"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: adding json files
        run: cat ./data/*.json > ./merged.json
